### ISSUE TITLE
[WEB]Erro com 2 submenus customizados

### ISSUE THREAD

**Issue by willedouglas** [PrisonGO/PrisonWeb#59]
Quando é inserido no dashboard 2 submenus customizados (subtree) ele abre os 2. E não pega a referência apenas de qual está sendo clicado.

**Comment by FelipeRubelBorges** [comment]
@willedouglas , coloca a imagem apontando o problema por gentileza.

**Comment by willedouglas** [comment]
Conforme contato com @jeanmmayer basta apenas mudar as referências do ng-init para resolver o problema.
